name: tcc_mobile #teste_requisicao
description: A new Flutter application.

publish_to: 'none'

  # sudo arch -x86_64 gem install ffi
  # go to ios folder then run
  # arch -x86_64 pod install

  # flutter build apk --split-per-abi
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main

version: 1.0.2+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
#  cloud_firestore: ^0.13.7
#  firebase_messaging: ^6.0.16
#  firebase_core: ^0.4.5
  cloud_firestore: ^4.10.0
  firebase_crashlytics: ^3.4.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.0


  auto_size_text: ^3.0.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  double_back_to_close_app: ^2.1.0
  provider: ^6.0.5
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.2
  flutter_vibrate: ^1.3.0
  page_transition: ^2.1.0


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/


flutter_icons:
  android: true
  ios: true
  image_path: "images/iconW.png"
